fixed mount plugin tutorial, as mentioned on tuwel
ElektraInitiative/libelektra pull request #3723
Opened 2021-03-23 21:10 UTC by philippoppel

Tuwel issue: https://tuwel.tuwien.ac.at/mod/forum/discuss.php?d=243029#p598964
 
closed issue #3722 & also added sudo to the first command, which is necessary anyway

## Basics

These points need to be fulfilled for every PR:

- [ x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

2021-03-25 23:16 UTC, kodebach approved these changes
LGTM

2021-03-25 23:17 UTC, mpranj commented
Thank you so much for the contribution. Please fix the merge conflict by rebasing from master.

@kodebach please review and merge if this fully resolves  #3722.

2021-03-29 07:53 UTC, markus2330 commented on doc/news/_preparation_next_release.md
> +- fixed #3722 _(Philipp Oppel)_
Thank you for the PR! This should be a "short descriptions of your changes" which is understandable by itself, like "Fixed tutorial ...". The reference to the issue can be there additionally.

2021-04-21 13:19 UTC, mpranj commented
Any news here?

This PR needs a rebase and has open review points.

2021-04-21 19:30 UTC, philippoppel commented
Hey, I rebased from master and added a better description, is it fine now?

2021-04-22 09:11 UTC, mpranj commented
Thank you! Your PR looks good, but there are still merge conflicts.

Are you sure you rebased from current upstream/master and not an outdated master branch? See the [docs](https://github.com/ElektraInitiative/libelektra/blob/master/doc/GIT.md#working-with-forks) for hints how to work with and sync forks.

2021-04-22 19:53 UTC, mpranj requested changes
Seems like something went wrong. There is a merge commit which should not be there when rebasing and the PR contains about 390 unrelated commits.

I created #3805, which is a rebased copy of this PR, as an example how it should look.

2021-04-23 18:14 UTC, philippoppel commented
thank you for fixing this, sorry for the hassle

when I tried rebasing to upstream/master it did work, but when I tried to push it, my IDE wanted me to merge otherwise my push was rejected. As far as I understood it, I should have reverted the merges I did before and make like a "clean" rebase, correct?

2021-04-23 20:18 UTC, closed without merging

2021-04-23 20:24 UTC, mpranj commented
Thank you for the PR and the documentation fixes! It was merged via #3805. 

> I should have reverted the merges I did before and make like a "clean" rebase, correct?

Afair I simply copied your branch and then rebased from upstream/master again and this already removed the merge commit. Then I fixed some merge errors that were done before (duplicate news entries).
If **nothing** else works another method is: create a new branch starting from upstream/master and then `git cherry-pick` all relevant commits. This is usually the last resort though.