Improve documentation of keyset.c with suggestions from API review
ElektraInitiative/libelektra pull request #3778
Opened 2021-04-14 20:20 UTC by lawli3t

## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

2021-04-16 15:58 UTC, mpranj commented
Thank you so much for all the PRs! :rocket: 

Regarding all your docu PRs: are they WIP or should we review?
Can you add release notes so the builds will go through? (Can also be done after reviews.)

2021-04-16 20:56 UTC, lawli3t commented
> Thank you so much for all the PRs! rocket
> 
> Regarding all your docu PRs: are they WIP or should we review?
> Can you add release notes so the builds will go through? (Can also be done after reviews.)

I've double-checked them now, I think I incorporated all my suggestions. Of course every change is up for debate, I hope the amount is not too overwhelming, I tried to mitigate that by splitting it up into modules. I will add the respective lines to the release notes!

2021-04-17 08:56 UTC, lawli3t commented
What would you think is an appropriate label? I think neither 'ready to merge' nor 'work in progress' seem appropriate from my point of view :thinking:

2021-04-17 09:07 UTC, mpranj commented
> What would you think is an appropriate label?

"ready to merge" is appropriate.

To keep it simple we used this approach: when you want a review you mark it as "ready to merge". This tells others that you do not plan any further changes. Whoever merges it should review it anyway. If everything is OK it will be merged, if not the reviewer requests changes and removes the "ready to merge" label.

It's basically stated at the end of the pull request template. Can we improve the template?

2021-04-17 10:02 UTC, lawli3t commented
I think i hung myself up too much on
> you also say that everything is ready to be merged.

it's fine

2021-04-17 13:35 UTC, mpranj requested changes
Great work! I like simple docs and this PR fixes lots of issues. :rocket: 

Please fix the formatting issues reported by the CI (for all PRs, there are some problems with trailing whitespace :wink:).
Hint: when the builds succeed, you can review the generated docs on [https://doc.libelektra.org/api/pr/](https://doc.libelektra.org/api/pr/) with the PR's number.

2021-04-17 13:35 UTC, mpranj commented on src/libs/elektra/keyset.c
> + * @p alloc to hint the size of the KeySet.
```suggestion
 * If the size of the KeySet is known in advance, use the
 * @p alloc parameter to hint the size of the KeySet.
```

2021-04-17 13:35 UTC, mpranj commented on src/libs/elektra/keyset.c
> + * application that you only need up to 15 Keys), use:
```suggestion
 * If your application only needs up to 15 Keys you can request a KeySet of size 15:
```

2021-04-17 13:35 UTC, mpranj commented on src/libs/elektra/keyset.c
> + * KeySet to another KeySet, for which this function
Nice, I like simple sentences :+1:

2021-04-17 13:35 UTC, mpranj commented on src/libs/elektra/keyset.c
> + * If this also matches, the Keys are found to be exactly the
`keyCompareByNameOwner`/`keyCompareByOwner` is now obsolete and very soon removed with a PR.
Also `memcmp` is used.

```suggestion
 * The comparison is based on a memcmp of the Key's names.
 * If the names match, the Keys are found to be exactly the
```

2021-04-17 13:35 UTC, mpranj commented on src/libs/elektra/keyset.c
> + * But then Key in the KeySet has another identity:
Maybe simpler: ?
```suggestion
 * You can duplicate the Key to avoid aliasing,
 * but then the Key in the KeySet has another identity:
```

2021-04-19 18:11 UTC, markus2330 approved these changes
Amazing work!

2021-04-19 18:11 UTC, markus2330 commented on src/libs/elektra/keyset.c
> + * @return -1 on an invalid internal cursor or after ksRewind
```suggestion
 * @retval -1 on an invalid internal cursor or after ksRewind
```

2021-04-20 11:56 UTC, mpranj commented
Needs rebase & has open conversations from review.

2021-04-21 03:00 UTC, lawli3t commented on src/libs/elektra/keyset.c
> + * If the size of the KeySet is known in advance, use the
not sure I follow a 100%, what exactly should be added to the glossary? KeySet itself?

2021-04-21 10:31 UTC, mpranj approved these changes

2021-04-21 13:04 UTC, merged

2021-04-21 13:11 UTC, mpranj commented
Thank you so much!

2021-05-01 05:58 UTC, markus2330 commented on src/libs/elektra/keyset.c
> + * If the size of the KeySet is known in advance, use the
Yes, how we use the word Key and KeySet. Please also link to the API, there are not so many links from our website to the API yet.