H3_Oppel_2
ElektraInitiative/libelektra pull request #3844
Opened 2021-05-12 09:03 UTC by philippoppel

## Basics

These points need to be fulfilled for every PR:

- [ x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ x] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

2021-05-17 09:08 UTC, markus2330 reviewed
Thank you! Please fix build server issues.

2021-05-17 09:08 UTC, markus2330 commented on src/plugins/length/README.md
> +# IP Address Validation
wrong copy&paste

2021-05-17 09:08 UTC, markus2330 commented on src/plugins/length/README.md
> +kdb mount config.dump /tests/length dump length
`TEST_REQUIRED_PLUGINS dump` needed in CMakeLists.txt

2021-05-17 09:08 UTC, markus2330 commented on src/plugins/length/README.md
> +- infos/metadata = check/length
```suggestion
- infos/metadata = check/length/max
```

as adding an additional check/length/min will be also useful at some point.

2021-05-17 09:08 UTC, markus2330 commented on src/plugins/length/length.c
> +#include <regex.h>
regex is not needed, please remove.

2021-05-17 09:08 UTC, markus2330 commented on src/plugins/length/length.c
> +		ELEKTRA_SET_VALIDATION_SEMANTIC_ERRORF (parentKey, "Validation of key %s with value %s failed", keyName (key),
Please improve the error message: write that the length check failed and with which length.

2021-05-17 09:08 UTC, markus2330 commented on src/plugins/length/test_length.h
> +#define PLUGIN_LEAKS_MEMORY (strcmp (PLUGIN_NAME, "network") == 0)
copy&paste error?

2021-05-17 09:08 UTC, markus2330 commented on src/plugins/length/testmod_length.c
> + * @brief Tests for lengthgth plugin
copy&paste error

2021-05-17 09:08 UTC, markus2330 commented on src/plugins/length/testmod_length.c
> +#define PLUGIN_NAME "lengthgth"
copy&paste error

2021-06-01 12:09 UTC, kodebach requested changes
In principle, this plugin is well written, but there are few major issue with the actual length validation part.
1. `Key`s can be binary. Your code does not take this into account at all. You basically have two options (both of which are acceptable, as long as they are properly documented in the README):
    - Don't support binary keys, and returns a descriptive error if a binary key is marked with `check/length`.
    - Fully support binary keys and validate their length correctly.
2. I don't know how much experience you have with C, but using a function like `sscanf` without proper error handling is not a good idea.
3. You shouldn't manually iterate over a string just to get its length. In general `strlen` is a better idea. It is easier to read and less error prone. Also Elektra already stores the sizes of key values, so no need to recalculate it.

Also, `ksRewind`/`ksNext` are deprecated (even though they aren't marked as such). We will accept the PR even, if you don't replace them, but since you have to change quite a bit of code anyway, it would be nice, if you could use the `for` loop I suggested instead.

2021-06-06 12:13 UTC, philippoppel commented on src/plugins/length/test_length.h
> +/**
I tried to do it as consistent to the other plugins as possible, I looked at ipaddr and did the same. But there is no other reason

2021-07-02 13:51 UTC, kodebach approved these changes

2021-07-02 14:30 UTC, kodebach commented
jenkins build libelektra please

2021-07-04 20:11 UTC, kodebach commented
@mpranj There seems to be some sort of permission issue on the Jenkins Server. Seems like not even pulling from Github works...

2021-07-05 08:04 UTC, closed without merging

2021-07-05 08:05 UTC, kodebach commented
Reopened as #3922