[FLOSS H2] doc: fix wording in DESIGN.md
ElektraInitiative/libelektra pull request #4155
Opened 2021-11-03 23:08 UTC by lawli3t

## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

2021-11-04 17:29 UTC, markus2330 requested changes
The content of all PRs are okay but in all of them the release notes were not yet updated.

2021-11-04 19:24 UTC, lawli3t commented
> The content of all PRs are okay but in all of them the release notes were not yet updated.
Sorry, it completely slipped my mind - probably because i was hurrying a bit too much

2021-11-10 11:34 UTC, muskater commented
Good work, I think this PR improves the syntactic correctness and the wording of this important document. While we are at it, you might want to consider to include the following two errors:

 
Line 9:
Elektra [aims](GOALS.md) at following design principles:
-1. To make the API **futureproof** so that it can remain compatible and stable
+1. To make the API **future-proof** so that it can remain compatible and stable
    over a long period of time,
 2. to make it hard to use the API the wrong way by making it simple&robust, and
 3. to make the API easy to use for programmers reading and writing

Line 43: 
The second function may also shut
-down connections. **Therefore** it must be called before the end of a program.
+down connections. **Therefore,** it must be called before the end of a program.

2021-11-10 11:40 UTC, muskater approved these changes
Good work, I think this PR improves the syntactic correctness and the wording of this important document. While we are at it, you might want to consider to include the following two errors:

Line 9:
Elektra aims at following design principles:
-1. To make the API futureproof so that it can remain compatible and stable
+1. To make the API future-proof so that it can remain compatible and stable
over a long period of time,
2. to make it hard to use the API the wrong way by making it simple&robust, and
3. to make the API easy to use for programmers reading and writing

Line 43:
The second function may also shut
-down connections. Therefore it must be called before the end of a program.
+down connections. Therefore, it must be called before the end of a program.

2021-11-10 11:40 UTC, muskater commented on doc/DESIGN.md
>  1. To make the API futureproof so that it can remain compatible and stable
My suggestions are:
Line 9: future-proof
Line 43: Therefore,

2021-11-10 13:39 UTC, JakobWonisch approved these changes
Good changes! The release notes have also now been update, so it looks good to go!

2021-11-13 17:15 UTC, markus2330 commented
jenkins build libelektra please

2021-11-13 17:16 UTC, markus2330 commented
There are a still a few CI errors.

2021-11-19 18:57 UTC, merged

2021-11-19 18:58 UTC, markus2330 commented
Thank you for the improvements!