[FLOSS H3] jna: extend HelloElektra #4093
ElektraInitiative/libelektra pull request #4173
Opened 2021-11-21 22:13 UTC by JakobWonisch

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

2021-11-30 19:40 UTC, muskater reviewed
Nice work, you wrote a comprehensive and easy to understand example. I think this is a nice addition to the Java-Language bindings. My only suggestions would be that you link the `issue` to this PR so it is easier to understand what your are trying to archive. You might also change the title of your PR into something a little bit more descriptive and add a small description in your main comment. The restyling issue should be easily fixable with a reformatting tool. All in all, you did a great job!

2021-12-01 00:11 UTC, lawli3t commented
Good PR, there seem to be some styling issues.

One thing I noticed apart from the suggestions from @4ydan is that maybe some comments in the Hello Elektra would be helpful? Not sure if it is necessary, because the functions itself should be explained in the core API documentation, but it would be a nice addition I think.

2021-12-09 15:12 UTC, markus2330 requested changes
Examples are very minimal and it is not so clear what they demonstrate.

2021-12-09 15:12 UTC, markus2330 commented on src/bindings/jna/hello/src/main/java/HelloElektra.java
> +    	ka = Key.create("user:/cutpoint/hello", "hiback"),
As build server says, there is a formatting problem.

2021-12-09 15:12 UTC, markus2330 commented on src/bindings/jna/hello/src/main/java/HelloElektra.java
> +	ka.setString("hibackagain");
Unclear that this is now a different example.

2021-12-09 15:12 UTC, markus2330 commented on src/bindings/jna/hello/src/main/java/HelloElektra.java
> +     	kc = Key.create("user:/different/hello", "hellothere");
Make more clear what this example shows:

```suggestion
     	kc = Key.create("user:/outside/cutpoint/hello", "hellothere");
```

2021-12-13 08:47 UTC, markus2330 commented
@lawli3t wrote:

> One thing I noticed apart from the suggestions from @4ydan is that maybe some comments in the Hello Elektra would be helpful? 

Do you mean @JakobWonisch here?

2022-01-18 13:02 UTC, markus2330 commented
Please fix styling issues.

2022-02-10 20:47 UTC, merged