[CM T1] Improve and extend the tutorial /doc/tutorials/specification.md
ElektraInitiative/libelektra pull request #4315
Opened 2022-04-03 23:48 UTC by flo91

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

2022-04-11 10:20 UTC, kodebach requested changes
Great work :+1: 

I have some suggestions to improve readability. There is also some overlap with #4319.

2022-04-11 18:35 UTC, kodebach commented
After talking to @markus2330, please also make sure that there is a shell recorder test for the specification tutorial (like `testshell_markdown_tutorial_merge` for the merge tutorial). It should just be a case of adding the CMake call to `add_msr_test` in the correct place...

2022-04-12 09:27 UTC, markus2330 commented
... and the correct place is tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt :rocket:

2022-04-27 14:36 UTC, kodebach commented
Regarding the failed `alpine` job: It seems the `date` plugin is explicitly excluded on Alpine Linux

https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/scripts/jenkins/Jenkinsfile#L691

I don't know why, I could try to include it. If it really doesn't work, you can either change the tutorial to use a different plugin, or exclude the test on Alpine (via CMake).

As for the ASAN failure: I think we need to add a new `no_sanitize` attribute to the hash function. Specifically, I think we need to add `no_sanitize("implicit-unsigned-integer-truncation")`. To do this, add a new CMake variable here:

https://github.com/ElektraInitiative/libelektra/blob/5702ce0496823fdd12c4e1e6ff9d6d1ca1b71a40/src/include/CMakeLists.txt#L138-L155

Then add the new `#define` here:

https://github.com/ElektraInitiative/libelektra/blob/5702ce0496823fdd12c4e1e6ff9d6d1ca1b71a40/src/include/kdbconfig.h.in#L61-L65

And finally, use the new attribute here:

https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/plugins/ni/nickel-1.1.0/src/hash.c#L329-L331

and here:

https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/plugins/ni/nickel-1.1.0/src/hash.c#L888-L890

2022-04-27 20:15 UTC, kodebach commented on tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
> +add_msr_test (tutorial_spec "${CMAKE_SOURCE_DIR}/doc/tutorials/specification.md")
```suggestion
add_msr_test (tutorial_spec "${CMAKE_SOURCE_DIR}/doc/tutorials/specification.md" PROPERTY LABELS memleak)
```

Seems like adding the `NO_SANITIZE` attributes didn't help. Please exclude the test from ASAN.

2022-04-28 03:26 UTC, flo91 commented
jenkins build libelektra please

2022-04-29 12:35 UTC, merged