[CM P1] JNA/Kotlin binding
ElektraInitiative/libelektra pull request #4352
Opened 2022-05-12 19:01 UTC by mandoway

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

---
Implements #4294

2022-05-20 13:02 UTC, kodebach requested changes
Mostly good APIs. Very good test coverage. Some APIs are a bit forced and unnecessary and sometimes there are duplicates.

I don't really like the way you introduced kotlinx.serialization APIs, please find a way to utilize kotlinx.serialization in a more standard way.

2022-05-21 13:37 UTC, markus2330 reviewed
Amazing job!

2022-05-21 15:15 UTC, markus2330 reviewed
Looked a bit more...

2022-05-21 15:15 UTC, markus2330 commented on src/bindings/jna/kotlin/src/test/kotlin/org/libelektra/key/GetKeyTest.kt
> +        assertEquals(key.byte, key.get())
also here, check if the underlying value is correct (and the next ones...)

2022-05-21 15:15 UTC, markus2330 commented on src/bindings/jna/kotlin/src/test/kotlin/org/libelektra/key/KeyBuilderTest.kt
> +        assertFailsWith<IllegalStateException> {
We would like to avoid such a possibility.

2022-05-21 15:15 UTC, markus2330 commented on src/bindings/jna/kotlin/src/main/kotlin/org/libelektra/keyExt/SetExt.kt
> +        set("", String::class)
Is this a silent conversion? Key's values can be null.

2022-05-21 15:31 UTC, merged