[CM T1] python binding: added .pop() .cut(), .head() and .tail() examples to keySet example
ElektraInitiative/libelektra pull request #4377
Opened 2022-06-15 05:40 UTC by leothetryhard

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

Continuation of #4321 after my fork broke. 
Now rebased with master with the suggested changes applied.

2022-06-15 12:01 UTC, kodebach requested changes
The examples for `cut` are good. The others functions are actually deprecated and will be removed soon. Please remove those examples and then we can merge this.

2022-06-15 14:37 UTC, markus2330 reviewed
Nice small cut/extend examples.

2022-06-15 14:37 UTC, markus2330 commented on src/bindings/swig/python/examples/example_keyset.py
> +print("Alternatively you can use pop")
@leothetryhard would be great if you can add deprecated notes or even better remove it from where you read that these functions are available.

2022-06-15 14:37 UTC, markus2330 commented on src/bindings/swig/python/examples/example_keyset.py
> +print("")
Yes, better to leave it.

2022-06-16 12:23 UTC, kodebach commented
Please rebase, so we can merge this PR too.

2022-06-17 09:02 UTC, merged