Add Python bindings for elektraMerge
ElektraInitiative/libelektra pull request #4448
Opened 2022-08-26 16:52 UTC by atmaxinger

Add KeySet merging functionality based on the elektraMerge library. The API is loosely based on the C++ kdb merging API. This is my first time with SWIG so I can't guarantee for anything 😂.

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

2022-08-27 16:11 UTC, markus2330 requested changes
Amazing work! :fireworks: Thanks for also adding tests! :revolving_hearts:

2022-08-27 16:20 UTC, markus2330 commented
@manuelm Do you have time for a review? Would be great to have your expertise for SWIG&Python here.

2022-08-28 13:30 UTC, atmaxinger commented on src/bindings/swig/python/merge.i
> +class ConflictStrategyAbort:
I wasn't sure about the minimum version of Python that we support, as enums first appeared in 3.4. AFAICT the bindings still support 2.7 (?)

2022-08-28 13:36 UTC, markus2330 commented on src/bindings/swig/python/merge.i
> +class ConflictStrategyAbort:
Python 2 support we definitely dropped long time ago (except of pythongen, which is obsolete now and waits to be removed, see #2987). Even Debian stable has Python 3.9, so Python 3.4 should be no problem at all.

Please add a check and documentation for which Python we require.

2022-08-28 13:44 UTC, atmaxinger commented on src/bindings/swig/python/merge.i
> +int getConflicts (ckdb::Key * informationKey);
how do I correctly update the symbols.map file?

2022-08-28 13:51 UTC, atmaxinger commented on src/bindings/swig/python/merge.i
> +int getConflicts (ckdb::Key * informationKey);
I guess I figured it out

2022-08-29 12:19 UTC, atmaxinger commented on src/bindings/swig/python/merge.i
> +class ConflictStrategyAbort:
Where would I add such a check?

2022-08-29 12:23 UTC, atmaxinger commented on src/bindings/swig/python/CMakeLists.txt
> +	else (CMAKE_VERSION VERSION_LESS 3.8)
@markus2330 @kodebach I just copied that from above. But I'm not sure if my eyes deceive me, but the conditions in the if () and else () are exactly the same !?, so none of that code will ever execute on CMAKE >= 3.8

2022-08-29 16:21 UTC, markus2330 commented on src/bindings/swig/python/merge.i
> +class ConflictStrategyAbort:
In the CMake file, excluding the whole binding on older Python versions.

2022-08-29 16:22 UTC, atmaxinger commented
@markus2330 Debian stretch and Ubuntu Xenial now fail because they have a cmake version < 3.8, which does not yet include `swig_add_library`

2022-08-30 13:51 UTC, markus2330 commented
> @markus2330 Debian stretch and Ubuntu Xenial now fail because they have a cmake version < 3.8, which does not yet include swig_add_library

It is time to say goodbye to them. Can you remove the Docker images, entries in Jenkinsfile etc.?

The required CMake version should be in the top-level CMakeLists.txt.

2022-08-30 14:16 UTC, atmaxinger commented
@markus2330 I changed the minimum required cmake version, but I think I can't do much about the Jenkins and Docker files right now, as the Jenkins build server currently has issues with the `docker login` command - every build fails because of that.

2022-08-30 17:13 UTC, markus2330 commented
Please report build server issues in #160.

@lukashartl do you know about this problem?

2022-08-31 08:00 UTC, manuelm commented
> @manuelm Do you have time for a review? Would be great to have your expertise for SWIG&Python here.

Hi. The swig part looks ok to me.

2022-08-31 20:20 UTC, atmaxinger commented
@markus2330 I have removed the now defunct docker images, but now the link check fails as an old news file references to one of the Dockerfiles. How should we handle this? I could remove the link but I'm not sure if modifying old news entries is the best idea.

```
Broken Links:
—————————————
/tmp/cirrus-ci-build/doc/news/2019-08-06_0.9.0.md:755:0 warning: invalid link '../../scripts/docker/debian/stretch/Dockerfile'
—————————————
```

2022-09-01 04:35 UTC, markus2330 commented
jenkins build libelektra please

2022-09-01 04:44 UTC, markus2330 commented
> How should we handle this?

Good point, seems like we do not have any docu about that. I created #4454

For this case: replace the link with https://git.libelektra.org/blob/799fecd94dcb482ea9338facaf63d39f8e5ab5bd/scripts/docker/debian/stretch/Dockerfile

2022-09-01 05:12 UTC, markus2330 commented
jenkins build libelektra please

2022-09-01 11:36 UTC, atmaxinger commented
jenkins build libelektra please

2022-09-02 07:42 UTC, atmaxinger commented
jenkins build libelektra please

2022-09-02 13:30 UTC, atmaxinger commented
jenkins build libelektra please

2022-09-02 20:54 UTC, atmaxinger commented
jenkins build libelektra please

2022-09-07 12:22 UTC, merged