[DRAFT] Mounting in C
ElektraInitiative/libelektra pull request #4626
Opened 2022-11-02 09:54 UTC by flo91

## Basics

early stage, work in progress, needs heavy refactoring, error handling not implemented yet,
**please do not review for now**

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [x] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

2022-11-04 17:46 UTC, markus2330 requested changes
Good to see first code! I added a few comments.

2022-11-04 17:46 UTC, markus2330 commented on src/include/kdbmount.h
> +struct cBackendInfo {
I don't think everything should start with c.

```suggestion
struct BackendInfo {
```

2022-11-04 17:46 UTC, markus2330 commented on src/include/kdbmount.h
> +/* from mountbase.cpp */
Mark this with TODO, as this should be removed later.

2022-11-04 17:46 UTC, markus2330 commented on src/include/kdbmount.h
> +const KeySet * cReadMountConf (bool clNull, bool clFirst, bool clSecond, bool clThird, bool clVerbose, bool clDebug);
Is this public API? Then it should start with a common prefix, e.g. elektraMount.

2022-11-04 17:46 UTC, markus2330 commented on src/include/kdbmount.h
> +void cOutputMtab (KeySet * const mountConf, bool clFirst, bool clSecond, bool clNull);
The API shouldn't output anything, please put this into the CLI.

2022-11-04 17:46 UTC, markus2330 commented on src/libs/elektra/cmount.c
> +/* Read mount configuration from the KDB
Please add full docu to public API.

2022-11-23 09:39 UTC, flo91 reviewed
Thanks for the useful notes!

2023-02-28 10:59 UTC, flo91 commented
The new PR #4851 contains is based on changes in the PR, so this PR represents a deprecated state and is now obsolete.
Additionally, instead of merging into master, the PR #4851 is for merging into `mount_cli_integration`.

2023-02-28 10:59 UTC, closed without merging