[FLOSS H2] Reinstate Mounting tutorial
ElektraInitiative/libelektra pull request #4646
Opened 2022-11-08 17:15 UTC by Bujuhu

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [x] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

2022-11-09 12:41 UTC, Dynamichost96 reviewed
# Review

### Documentation is introductory, concise, good to read and describes everything what the PR does
The documentation fulfills the criteria the changed sentences are easier to read and understand, in comparison to the prior.

### Examples are well chosen and understandable
No new Examples where provided. 

### Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
No code was added.

### APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
No code was added.

### Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)
No code was added.

2022-11-09 20:09 UTC, stefnotch requested changes

2022-11-09 20:09 UTC, stefnotch commented on doc/tutorials/mount.md
> +To use elketra with non-elektrified applications we can also let Elektra sync configuration files on the file system and the elektra key-storage.
Typo here, `elketra` should be `Elektra`

2022-11-10 12:05 UTC, markus2330 requested changes
Great job, please fix the spelling mistakes and add them to scripts/sed.

2022-11-10 12:05 UTC, markus2330 commented on doc/tutorials/mount.md
> +To use Elketra with non-elektrified applications we can also let Elektra sync configuration files on the file system and the Elektra key-storage.
```suggestion
To use Elektra with non-elektrified applications we can also let Elektra sync configuration files on the file system and  Elektra's key-value storage.
```

2022-11-22 09:44 UTC, markus2330 commented
jenkins build libelektra please

2022-11-22 16:18 UTC, merged

2022-11-22 16:18 UTC, markus2330 commented
Great job!