[FLOSS H2] Spelling fix for older releases-news
ElektraInitiative/libelektra pull request #4653
Opened 2022-11-09 12:50 UTC by Dynamichost96

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

2022-11-09 20:07 UTC, stefnotch requested changes
Oh, did the classic thing happen where 
1. one works on some code
2. then starts a pull request,
3. and then creates a branch from there (*instead of creating a branch from the main*), and keeps working on the code
4. starts another pull request https://github.com/ElektraInitiative/libelektra/pull/4655

I mean, it's not a problem. I just find it amusing, because I keep doing the same thing myself despite not intending to.

2022-11-09 20:07 UTC, stefnotch commented on doc/news/2020-05-26_0.9.2.md
> +- CSV storage
I think this change should be reverted, since it refers to a specific plugin name.
https://www.libelektra.org/plugins/csvstorage

2022-11-09 20:24 UTC, Dynamichost96 commented
> Oh, did the classic thing happen where
> 
> 1. one works on some code
> 2. then starts a pull request,
> 3. and then creates a branch from there (_instead of creating a branch from the main_), and keeps working on the code
> 4. starts another pull request #4655
> 
> I mean, it's not a problem. I just find it amusing, because I keep doing the same thing myself despite not intending to.

Yes you are completely right, I branched from a different Branche instead form the main :D

2022-11-13 03:47 UTC, flo91 commented
@Dynamichost96 
Please add prefixes to the commit-messages (e.g. "doc: ", can be done with `reword` while interactively rebasing)

2023-01-16 19:31 UTC, markus2330 commented on doc/news/2020-10-30_0.9.3.md
> +- Increased CTest timeout for `testscr_check_kdb_internal_suite` due to timeouts reached on slow test machines. _(Mihael Pranjić)_
nice catch.

Rebase is missing here.

2023-01-22 21:19 UTC, closed without merging