[FLOSS H2] Spelling fix for Tutorial-Documentation
ElektraInitiative/libelektra pull request #4655
Opened 2022-11-09 14:56 UTC by Dynamichost96

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

2022-11-09 20:02 UTC, stefnotch requested changes

2022-11-09 20:02 UTC, stefnotch commented on doc/news/2020-05-26_0.9.2.md
> +- CSV storage
I think this change should be reverted, since it refers to a specific plugin name.
https://www.libelektra.org/plugins/csvstorage

2022-11-09 20:07 UTC, stefnotch commented on doc/news/2020-05-26_0.9.2.md
> +- CSV storage
Lovely, thank you!

2022-11-09 20:08 UTC, stefnotch approved these changes

2022-11-10 17:01 UTC, markus2330 commented
Looks great. Can you also add these spelling errors to scripts/sed?

2022-11-10 17:05 UTC, Dynamichost96 commented
> Looks great. Can you also add these spelling errors to scripts/sed?

Thank you. yes for sure  I'm on it :)

2022-11-13 03:31 UTC, flo91 commented
@markus2330 
> Looks great. Can you also add these spelling errors to scripts/sed?

Are you sure you want to change the spelling from `metakey` to `meta key`, from `metavalue` to `meta value`, from `keyname` to `key name` and from `mountpoint` to `mount point`?

Currently, at least for the `meta*`-terms, the variants without spaces are defined in the sed-script:
https://github.com/ElektraInitiative/libelektra/blob/0f0a78a76b79b3d195723458fe38e5cc1ac3f9d0/scripts/sed#L54-L57

2022-11-13 03:46 UTC, flo91 commented
@Dynamichost96 
Please clean up the commits-history (squash commits) and add prefixes to the commit-messages (e.g. "doc: ", can be done with reword while interactively rebasing)

2022-11-14 10:32 UTC, markus2330 commented
> Are you sure you want to change the spelling from metakey to meta key, from metavalue to meta value, from keyname to key name and from mountpoint to mount point?

I don't think that such a change is needed. In any case it shouldn't be done in parts (either everywhere or nowhere).

2023-01-15 22:42 UTC, closed without merging