[FLOSS H2] Add source documentation
ElektraInitiative/libelektra pull request #4662
Opened 2022-11-09 16:25 UTC by Eiskasten

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

2022-11-13 02:29 UTC, flo91 requested changes

2022-11-13 02:29 UTC, flo91 commented on src/libs/elektra/key.c
> + * Frees the `key`, `ukey` and `data.v` fields from the provided key parameter, if the `KEY_FLAG_MMAP_KEY` is not set.
```suggestion
 * Frees the `key`, `ukey` and `data.v` fields from the provided `key` parameter.
 * `key` and `ukey` are only freed if the flag `KEY_FLAG_MMAP_KEY` is NOT set.
 * `data.v` is only freed if the flag `KEY_FLAG_MMAP_DATA` is NOT set.
```

2022-11-17 08:50 UTC, markus2330 commented
jenkins build libelektra please

2022-11-21 03:17 UTC, flo91 approved these changes

2022-11-22 01:28 UTC, flo91 commented
jenkins build libelektra please

2022-11-22 05:34 UTC, markus2330 commented
jenkins build libelektra please

2022-11-22 16:37 UTC, markus2330 reviewed
Good that you a added a bit of documentation. "atomic" unfortunately is unclear to me.

2022-11-22 16:37 UTC, markus2330 commented on src/libs/elektra/key.c
> + * The checks are made separately which makes this call not atomic.
What do you mean by this? I don't see any return path that would lead to an inconsistent state.

2022-11-22 16:37 UTC, markus2330 commented on src/libs/elektra/key.c
> + * `data.v` is only freed if the flag `KEY_FLAG_MMAP_DATA` is NOT set.
This is a bit too low-level. How the struct fields are called and the existence of MMAP flags are IMHO implementation details.

2022-11-23 22:31 UTC, flo91 commented
@Eiskasten Please adapt the documentation of `static void keyClearNameValue (Key * key)` as requested by @markus2330.

2023-03-28 09:51 UTC, closed without merging