docs: harmonize spelling of Git
ElektraInitiative/libelektra pull request #4680
Opened 2022-11-14 16:20 UTC by joni1993

Fixes #4679 4679

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

2022-11-17 08:48 UTC, markus2330 commented
Ahh, was it maybe by accident that doc/Git.md ended up in #4634?

As said over there: please make sure that doc/GIT.md gets a proper rename to doc/Git.md (e.g. by using `git mv`).

2022-12-04 18:57 UTC, flo91 requested changes

2022-12-04 18:57 UTC, flo91 commented on doc/TESTING.md
> +`-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`. This way `CMake` creates a file called `compile_commands.json` in
I'd only put `cmake` (the command, lowercase) in `code`-tags.
```suggestion
To analyze the whole project, use it in conjunction with CMake by calling `cmake` with the parameter
`-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`. This way CMake creates a file called `compile_commands.json` in
```

2022-12-04 18:57 UTC, flo91 commented on doc/news/2016-11-22_0.8.19.md
> +Elektra should work on every system that has `CMake` and a `C/C++` compiler.
```suggestion
Elektra should work on every system that has CMake and a C/C++ compiler.
```

2022-12-07 08:54 UTC, deoknats861 commented
### Review
**Current CI situation**
Cirrus CI failes due to broken links. As I could not reproduce this issue locally, I would recommend to rerun the check but I do not know if there is already a solution for that (see [issue 4669](https://github.com/ElektraInitiative/libelektra/issues/4669) for updates).
Regarding the Jenkins build fail I cannot see exactly why it is failing. There were some errors for generated man pages, maybe there is a problem with that. I could also imagine that this is an internal Jenkins issue exclusively.

**Documentation**
The PR title and the the changes made to the notes for the next release speak are clear and describe everything that was changed in this PR. 

**Examples are well chosen and understandable**
There were no examples added.

**Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)**
No code was added.

**APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)**
No API was added.

**Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)**
No code was added.

2022-12-07 14:32 UTC, deoknats861 commented
Update: The CI problems occurred due to https://github.com/ElektraInitiative/libelektra/issues/4752

You can fix it be rebasing with the current master and repushing to your branch. CI should then succeed :)

2022-12-11 15:38 UTC, flo91 approved these changes

2022-12-11 16:18 UTC, flo91 commented
jenkins build libelektra please

2022-12-19 11:12 UTC, merged

2022-12-19 11:12 UTC, markus2330 commented
Great job!