[FLOSS H3] csvstorage: fix silent failure on meta-key insertion
ElektraInitiative/libelektra pull request #4725
Opened 2022-11-29 12:10 UTC by Bujuhu

fixes #4586

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

2022-11-30 14:23 UTC, Dynamichost96 commented
Documentation is introductory, concise, good to read and describes everything what the PR does
CI fails due to out of memory error I assume this should not be related to the code changed!

Examples are well chosen and understandable
N/A

Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
Code is conforming to the Guidelines

APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
N/A

Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)
Code is consistent to the Guidelines

2022-12-04 19:32 UTC, flo91 commented on src/plugins/csvstorage/testmod_csvstorage.c
> +	ksDel (ks);
Please also delete the `conf` keyset.
```suggestion
	ksDel (conf);
	ksDel (ks);
```

2022-12-04 19:34 UTC, flo91 requested changes
~Please also delete the `conf` keyset.~

2022-12-11 20:07 UTC, flo91 requested changes

2022-12-11 20:07 UTC, flo91 commented on src/plugins/csvstorage/testmod_csvstorage.c
> +	ksDel (conf);
Sorry, your solution was correct!

You used the macro `PLUGIN_OPEN(NAME)` which calls the function `elektraPluginOpen(...)` with the KeySet `conf` as argument.
https://github.com/ElektraInitiative/libelektra/blob/6a6d1bf57cc50348cbfbe9c94da7dc39c67969ad/tests/cframework/tests_plugin.h#L14-L22

There, the KeySet is assigned to an internal variable:
https://github.com/ElektraInitiative/libelektra/blob/6a6d1bf57cc50348cbfbe9c94da7dc39c67969ad/src/libs/elektra/plugin.c#L92

At the end of your test, the `PLUGIN_CLOSE()` macro is called and there `ksDel (handle->conf)` is done:

https://github.com/ElektraInitiative/libelektra/blob/6a6d1bf57cc50348cbfbe9c94da7dc39c67969ad/src/libs/elektra/plugin.c#L135


```suggestion
```

2022-12-11 20:08 UTC, flo91 approved these changes

2022-12-12 16:53 UTC, merged