[FLOSS H3] links: Replace tons of http with https
ElektraInitiative/libelektra pull request #4734
Opened 2022-11-30 20:03 UTC by Eiskasten

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

2022-12-05 10:24 UTC, markus2330 commented
Thank you for the PR!

Does this replace all http:// links? Which ones are missing?

2022-12-06 20:32 UTC, Bujuhu requested changes
Remember to add your changes to docs/news/_prepare_next_release.md

2022-12-07 00:18 UTC, Eiskasten commented on doc/WHO.md
> -- [LCDproc](http://lcdproc.omnipotent.net/) (in progress)
You are right, the cert is only valid for different subdomains.

2022-12-07 00:22 UTC, Eiskasten commented
> Thank you for the PR!
> 
> Does this replace all http:// links? Which ones are missing?

Not all links are replaced. There are three main reasons why not all links can be replaced:

- there is no https link available
- the http link is part of a xml namespace, https links are per definition another namespace
- the link is part of a license or included library which may result in an incorrect license detection

2022-12-11 16:43 UTC, flo91 commented
@Eiskasten 
Please rebase and resolve the merge-conflict in the file `src/tools/website/README.md`.

2023-01-11 10:40 UTC, markus2330 commented
@Eiskasten please rebase

2023-01-14 18:34 UTC, markus2330 commented
@Eiskasten not all man pages were regenerated.

2023-01-15 06:48 UTC, markus2330 commented
I think you need to keep the http link for lcdproc.omnipotent.net, their https setup seems to be broken.

2023-01-16 11:31 UTC, merged

2023-01-16 11:31 UTC, markus2330 commented
Perfect, all is well now!