[FLOSS H3] mozprefs: Fixing silent failing for mozprefs plugin
ElektraInitiative/libelektra pull request #4772
Opened 2022-12-13 15:39 UTC by Dynamichost96

Fixes #4585

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

2022-12-15 13:34 UTC, Janldeboer reviewed
Good change!
Reading through the code all the changes seem appropriate to fix the mentioned issues.
Just run the format patches proposed by the `continuous-integration/jenkins/pr-merge` check to fix the format.
I wonder why only one check was run?

2023-01-11 10:57 UTC, flo91 requested changes
Thank you for the PR!
Please fix the styling issues as reported by the CI (you can apply the patch provided by the CI), clean up the commit history (rebase!) and answer the questions of my review.

2023-01-11 10:57 UTC, flo91 commented on doc/news/_preparation_next_release.md
> +-Fixed bug when inserting Metakeys it would fail silently _(Nikola Prvulovic @Dynamichost96)_
```suggestion
-Fixed bug: When inserting unknown meta keys it failed silently _(Nikola Prvulovic @Dynamichost96)_
```

2023-01-11 10:57 UTC, flo91 commented on src/plugins/mozprefs/mozprefs.c
> +			if (elektraStrNCmp (pos, "meta:/internal/mozprefs", 19) != 0 && elektraStrCmp (pos, "meta:/origname") && elektraStrNCmp (pos, "meta:/rename", 12) != 0 && elektraStrCmp (pos, "meta:/binary") != 0)
Why did you only compare the first 19 characters in `elektraStrNCmp (pos, "meta:/internal/mozprefs", 19)`?

Please use a consistent coding style (`elektraStrCmp (pos, "meta:/origname")` was not explicitly compared against `0`).

```suggestion
			if (elektraStrNCmp (pos, "meta:/internal/mozprefs", 23) != 0 && elektraStrCmp (pos, "meta:/origname") != 0 && elektraStrNCmp (pos, "meta:/rename", 12) != 0 && elektraStrCmp (pos, "meta:/binary") != 0)
```

2024-01-27 01:43 UTC, closed without merging