doc: add additional use cases for Key in libelektra-core
ElektraInitiative/libelektra pull request #4838
Opened 2023-01-30 22:19 UTC by lawli3t

… key

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

2023-03-12 20:48 UTC, kodebach requested changes
LGTM, just some minor things

2023-03-12 20:48 UTC, kodebach commented on doc/usecases/core/UC_key_base_name.md
> +  - Caller requests to append to name of `Key`
```suggestion
  - Caller requests to append new name part to `Key`
```

2023-03-12 20:48 UTC, kodebach commented on doc/usecases/core/UC_key_clear.md
> +  - Caller requests the fields of a `Key` should get cleard
```suggestion
  - Caller requests the data of a `Key` should get cleared
```

Data as in "what's publicly visible", some internal fields could remain or be set to specific values (e.g. sync flag).

2023-03-12 20:48 UTC, kodebach commented on doc/usecases/core/UC_key_copy.md
> +  - Fields, that caller wanted to copy, of `Key` k2 now have the value of the respective fields of `Key` k1
```suggestion
  - Caller requests to copy some or all data (name, value, metadata) from `Key` k1 to `Key` k2
  - The data, that caller wanted to copy, of `Key` k2 now have the value of the respective fields of `Key` k1
```

2023-03-12 20:48 UTC, kodebach commented on doc/usecases/core/UC_key_lock.md
> +  - Possible lock flags are: name, value, metadata
```suggestion
  - Caller requests lock status of one or multiple flags (name, value, metadata) of a `Key`
```

2023-03-12 20:48 UTC, kodebach commented on doc/usecases/core/UC_key_ref.md
> +- **Non-functional Constraints:**
The range `0 - INT_MAX` is wrong, all refs are `uint16_t` so it should be

```suggestion
- **Error scenario:**
  - Caller requests to increment value of reference counter of a `Key` whose reference counter is UINT16_MAX
  - Reference counter will not get incremented and stays at UINT16_MAX
- **Error scenario:**
  - Caller requests to decrement value of reference counter of a `Key` whose reference counter is 0
  - Reference counter will not get decremented and stays at 0
- **Postcondition:**
  - Reference Counter has a value from 0 to UINT16_MAX
- **Non-functional Constraints:**
```

2023-03-16 22:44 UTC, lukashartl approved these changes

2023-07-02 17:24 UTC, merged

2023-07-02 17:24 UTC, markus2330 commented
Thank you!